# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Windows and macOS builds.

Shared between both platforms (see .github/workflows/windows-macos-build.yml,
which runs `pyinstaller packaging/cwrobot.spec` on both) so there's one
place to keep the Analysis/hidden-import list in sync, with platform
differences (icon format, macOS .app bundling) branched on sys.platform
below. This is NOT used by the Linux AppImage build -- that has its own,
unrelated path via packaging/build_appimage.sh -- so nothing here touches
that build.

Icons: expects packaging/build/cwrobot.ico (Windows) and
packaging/build/cwrobot.icns (macOS) to already exist -- generated by a
prior CI step (see the workflow) from assets/icon-256.png. Falls back to
no icon if the expected file isn't there, so a local test build without
having run the icon-generation step still works.
"""

import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_all

REPO_ROOT = Path(SPECPATH).resolve().parent  # noqa: F821 -- SPECPATH is injected by PyInstaller
ENTRY_SCRIPT = str(REPO_ROOT / "packaging" / "pyinstaller_entry.py")
ICON_DIR = REPO_ROOT / "packaging" / "build"

APP_NAME = "cwrobot"
APP_DISPLAY_NAME = "CW Robot"

datas = []
binaries = []
hiddenimports = []
# pyinstaller-hooks-contrib ships hooks for all three, but collect_all
# additionally guarantees every Qt platform plugin (including
# "offscreen", which --smoke-test runs under in CI) and PortAudio's
# bundled native library actually make it into the frozen build.
for pkg in ("PySide6", "scipy", "sounddevice"):
    pkg_datas, pkg_binaries, pkg_hiddenimports = collect_all(pkg)
    datas += pkg_datas
    binaries += pkg_binaries
    hiddenimports += pkg_hiddenimports

a = Analysis(  # noqa: F821
    [ENTRY_SCRIPT],
    pathex=[str(REPO_ROOT / "src")],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)  # noqa: F821

if sys.platform == "darwin":
    icon_path = ICON_DIR / "cwrobot.icns"
else:
    icon_path = ICON_DIR / "cwrobot.ico"
icon_file = str(icon_path) if icon_path.is_file() else None

exe = EXE(  # noqa: F821
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    strip=False,
    upx=False,
    console=False,
    icon=icon_file,
)

coll = COLLECT(  # noqa: F821
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name=APP_NAME,
)

if sys.platform == "darwin":
    app = BUNDLE(  # noqa: F821
        coll,
        name=f"{APP_DISPLAY_NAME}.app",
        icon=icon_file,
        bundle_identifier="hu.dacr.cwrobot",
        info_plist={
            "CFBundleName": APP_DISPLAY_NAME,
            "CFBundleDisplayName": APP_DISPLAY_NAME,
            # Kept in sync with the "About" dialog's version in
            # cwrobot.ui.main_window (the project's actual release-version
            # convention -- git tags/pyproject.toml's own version field
            # lag behind it) -- bump this alongside that string.
            "CFBundleShortVersionString": "1.0.11",
            "NSHighResolutionCapable": True,
            # sounddevice/PortAudio opens the microphone; without this key
            # macOS's TCC privacy prompt never appears and the open just
            # fails silently.
            "NSMicrophoneUsageDescription": "CW Robot needs microphone access to receive audio from your radio.",
        },
    )
